import {StyleSheet} from 'react-native';
import colors from '../../styles/colors';

export const styles = StyleSheet.create({
  container: {
    width: 284,
    paddingBottom: 12,
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: 8,
    borderRadius: 8,
    backgroundColor: colors.white,
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    marginBottom: 30,
    elevation: 4,
  },
  rowImages: {
    flexDirection: 'row',
  },
  firstImage: {
    width: '66%',
    height: 141 + 3,
    borderTopLeftRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.lc_connect_blue,
  },
  smallImage: {
    width: 284 * 0.33,
    height: 141 / 2,
    marginLeft: 3,
    marginBottom: 3,
    borderTopRightRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.lc_connect_blue,
  },
  secondSmallImage: {
    width: 284 * 0.33,
    height: 141 / 2,
    marginLeft: 3,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.lc_connect_blue,
  },
  viewAdsTitle: {
    width: '100%',
  },
  proContainer: {
    flexDirection: 'row',
    height: 24,
    paddingHorizontal: 4,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 4,
    borderRadius: 8,
    borderWidth: 1,
    marginLeft: 12,
    marginRight: 12,
  },
  adsTitle: {
    marginLeft: 12,
    marginRight: 12,
    color: colors.blackPro,
    textAlign: 'left',
    fontFamily: 'Open Sans',
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 22,
  },
  viewInfo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginLeft: 12,
    marginRight: 12,
  },
  distanceContainer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    width: '50%',
    gap: 4,
  },
  separator: {
    height: 1,
    alignSelf: 'stretch',
    borderRadius: 10,
    opacity: 0.5,
    marginLeft: 12,
    marginRight: 12,
    backgroundColor: colors.grey_super_light,
  },
  rowPrice: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 12,
    marginRight: 12,
  },
  infoItemIcon: {
    width: 16,
    height: 16,
  },
  infoIcon: {
    width: 12,
    height: 12,
  },
  infoButton: {
    width: 30,
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  distanceText: {
    color: colors.blackPro,
    textAlign: 'center',
    fontFamily: 'Open Sans',
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 20,
    textAlignVertical: 'center',
    marginLeft: 4,
  },
  favoritesButton: {
    margin: 15,
    width: 40,
    height: 40,
    position: 'absolute',
    right: 10,
    top: 0,
    borderRadius: 20,
    opacity: 0.9,
    justifyContent: 'center',
    alignItems: 'center',
  },
  favoritesIcon: {
    width: 24,
    height: 24,
  },
  geolocOutlined: {
    width: 16,
    height: 16,
  },
  priceTotal: {
    color: colors.blackPro,
    textAlign: 'center',
    fontFamily: 'Open Sans',
    fontSize: 22,
    fontWeight: '600',
    lineHeight: 28,
  },
  orText: {
    color: colors.blackPro,
    fontFamily: 'Open Sans',
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 20,
    maxWidth: '100%',
    marginLeft: 5,
    marginRight: 5,
  },
  monthlyPrice: {
    overflow: 'hidden',
    color: colors.blackPro,
    fontFamily: 'Open Sans',
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 20,
  },
  bonneAffaireText: {
    color: colors.textDeal,
    textAlign: 'center',
    fontFamily: 'Open Sans',
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 20,
    textAlignVertical: 'center',
    marginLeft: 4,
  },
  leftTopRow: {
    flexDirection: 'row',
    position: 'absolute',
    left: 10,
    top: 13,
  },
  viewTag: {
    flexDirection: 'row',
    height: 20,
    paddingVertical: 2,
    paddingHorizontal: 4,
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 4,
    borderRadius: 5,
    backgroundColor: colors.white,
  },
  labelTag: {
    color: colors.blackPro,
    textAlign: 'center',
    textAlignVertical: 'center',
    fontFamily: 'Open Sans',
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 14,
  },
});
